FROM rust:1.80-slim-bookworm AS base

RUN apt-get update && apt-get upgrade -y && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

####################
FROM base as builder

WORKDIR /app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/actix-web-api /usr/local/bin/atxapi

ENTRYPOINT ["atxapi"]
