FROM rust:1.80-slim-bookworm AS base

RUN apt update && apt upgrade -y && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

FROM base AS builder

WORKDIR /app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /app/target/release/axum-api /app/axum-api

ENTRYPOINT ["bash"]
