FROM rust:1.80-slim-bookworm AS base

RUN apt-get update && apt-get upgrade -y && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

####################
FROM base AS builder

WORKDIR /app

COPY . .

RUN cargo build --release

#########################
FROM debian:bookworm-slim

COPY --from=builder /app/target/release/axum-api /usr/local/bin/xmapi

ENTRYPOINT ["xmapi"]
