FROM rust:1.79 as base

RUN apt update && apt upgrade -y

FROM base as builder

WORKDIR /usr/src/app

COPY . .

RUN cargo install --path .

FROM debian:bookworm-slim as runner

COPY --from=builder /usr/local/cargo/bin/rocket-api /usr/local/bin/rocket-api

ENV ROCKET_ADDRESS=0.0.0.0 ROCKET_PORT=8000

EXPOSE ${ROCKET_PORT}

CMD ["rocket-api"]
