FROM rust:1.80-slim-bookworm AS base

RUN apt-get update && apt-get upgrade -y && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

####################
FROM base AS builder

WORKDIR /app

COPY . .

RUN cargo build --release

#########################
FROM debian:bookworm-slim

COPY --from=builder /app/target/release/rocket-api /usr/local/bin/rapi

ENV ROCKET_ADDRESS=0.0.0.0 ROCKET_PORT=8000

EXPOSE ${ROCKET_PORT}

ENTRYPOINT ["rapi"]
